-- Seed: Bulgarian accredited HEIs (51 institutions)
-- Generated from NACID registry + research report, 2026-04-24
-- accreditation_until is not in the schema yet — omitted intentionally

-- Remove any development stubs that differ from canonical slugs
DELETE FROM institution WHERE slug = 'su-kliment-ohridski';

INSERT INTO institution (slug, name_bg, name_en, short_name_bg, ownership, city, website_url, admissions_url)
VALUES
-- ── State universities ────────────────────────────────────────────────────────
('su-sofia',
 'Софийски университет „Св. Климент Охридски"',
 'Sofia University "St. Kliment Ohridski"',
 'СУ', 'state', 'София',
 'https://www.uni-sofia.bg',
 'https://www.uni-sofia.bg/index.php/bul/priem'),

('unss-sofia',
 'Университет за национално и световно стопанство',
 'University of National and World Economy',
 'УНСС', 'state', 'София',
 'https://www.unwe.bg',
 'https://priem.unwe.bg'),

('pu-plovdiv',
 'Пловдивски университет „Паисий Хилендарски"',
 'Plovdiv University "Paisii Hilendarski"',
 'ПУ', 'state', 'Пловдив',
 'https://uni-plovdiv.bg',
 'https://uni-plovdiv.bg/pages/index/566/'),

('vtu-vt',
 'Великотърновски университет „Св. св. Кирил и Методий"',
 'St. Cyril and St. Methodius University of Veliko Turnovo',
 'ВТУ', 'state', 'Велико Търново',
 'https://www.uni-vt.bg',
 'https://priemunivt.bg'),

('swu-blagoevgrad',
 'Югозападен университет „Неофит Рилски"',
 'South-West University "Neofit Rilski"',
 'ЮЗУ', 'state', 'Благоевград',
 'https://www.swu.bg',
 NULL),

('shu-shumen',
 'Шуменски университет „Епископ Константин Преславски"',
 'Konstantin Preslavsky University of Shumen',
 'ШУ', 'state', 'Шумен',
 'https://www.shu.bg',
 NULL),

('ru-ruse',
 'Русенски университет „Ангел Кънчев"',
 'Angel Kanchev University of Ruse',
 'РУ', 'state', 'Русе',
 'https://www.uni-ruse.bg',
 'https://www.uni-ruse.bg/admission'),

('bdu-burgas',
 'Бургаски държавен университет „Проф. д-р Асен Златаров"',
 'Burgas State University "Prof. Dr. Assen Zlatarov"',
 'БДУ', 'state', 'Бургас',
 'https://uniburgas.bg',
 NULL),

('tru-starazagora',
 'Тракийски университет',
 'Trakia University',
 'ТрУ', 'state', 'Стара Загора',
 'https://trakia-uni.bg',
 'https://trakia-uni.bg/priem'),

('ue-varna',
 'Икономически университет — Варна',
 'University of Economics — Varna',
 'ИУ', 'state', 'Варна',
 'https://ue-varna.bg',
 NULL),

('sa-svishtov',
 'Стопанска академия „Д. А. Ценов"',
 'D. A. Tsenov Academy of Economics',
 'СА', 'state', 'Свищов',
 'https://www.uni-svishtov.bg',
 NULL),

('tu-sofia',
 'Технически университет — София',
 'Technical University of Sofia',
 'ТУ-С', 'state', 'София',
 'https://www.tu-sofia.bg',
 'https://priem.tu-sofia.bg'),

('tu-varna',
 'Технически университет — Варна',
 'Technical University of Varna',
 'ТУ-В', 'state', 'Варна',
 'https://www1.tu-varna.bg',
 'https://ksp.tu-varna.bg'),

('tu-gabrovo',
 'Технически университет — Габрово',
 'Technical University of Gabrovo',
 'ТУ-Г', 'state', 'Габрово',
 'https://www.tugab.bg',
 NULL),

('uacg-sofia',
 'Университет по архитектура, строителство и геодезия',
 'University of Architecture, Civil Engineering and Geodesy',
 'УАСГ', 'state', 'София',
 'https://www.uacg.bg',
 NULL),

('uctm-sofia',
 'Химикотехнологичен и металургичен университет',
 'University of Chemical Technology and Metallurgy',
 'ХТМУ', 'state', 'София',
 'https://www.uctm.edu',
 NULL),

('mgu-sofia',
 'Минно-геоложки университет „Св. Иван Рилски"',
 'University of Mining and Geology "St. Ivan Rilski"',
 'МГУ', 'state', 'София',
 'https://mgu.bg',
 NULL),

('ltu-sofia',
 'Лесотехнически университет',
 'University of Forestry',
 'ЛТУ', 'state', 'София',
 'https://ltu.bg',
 NULL),

('au-plovdiv',
 'Аграрен университет — Пловдив',
 'Agricultural University — Plovdiv',
 'АУ', 'state', 'Пловдив',
 'https://www.au-plovdiv.bg',
 NULL),

('uft-plovdiv',
 'Университет по хранителни технологии',
 'University of Food Technologies',
 'УХТ', 'state', 'Пловдив',
 'https://uft-plovdiv.bg',
 NULL),

('mu-sofia',
 'Медицински университет — София',
 'Medical University of Sofia',
 'МУ-С', 'state', 'София',
 'https://mu-sofia.bg',
 'https://admission.mu-sofia.bg'),

('mu-plovdiv',
 'Медицински университет — Пловдив',
 'Medical University of Plovdiv',
 'МУ-П', 'state', 'Пловдив',
 'https://mu-plovdiv.bg',
 'https://mu-plovdiv.bg/priem/'),

('mu-varna',
 'Медицински университет „Проф. д-р Параскев Стоянов" — Варна',
 'Medical University of Varna "Prof. Dr. Paraskev Stoyanov"',
 'МУ-В', 'state', 'Варна',
 'https://www.mu-varna.bg',
 NULL),

('mu-pleven',
 'Медицински университет — Плевен',
 'Medical University of Pleven',
 'МУ-Пл', 'state', 'Плевен',
 'https://mu-pleven.bg',
 NULL),

('nsa-sofia',
 'Национална спортна академия „Васил Левски"',
 'National Sports Academy "Vasil Levski"',
 'НСА', 'state', 'София',
 'https://www.nsa.bg',
 NULL),

('nha-sofia',
 'Национална художествена академия',
 'National Academy of Art',
 'НХА', 'state', 'София',
 'https://nha.bg',
 'https://nha.bg/bg/kategoriq/kandidatstvane'),

('nma-sofia',
 'Национална музикална академия „Проф. Панчо Владигеров"',
 'National Academy of Music "Prof. Pancho Vladigerov"',
 'НМА', 'state', 'София',
 'http://www.nma.bg',
 NULL),

('natfiz-sofia',
 'Национална академия за театрално и филмово изкуство „Кръстьо Сарафов"',
 'National Academy for Theatre and Film Arts "Krastyo Sarafov"',
 'НАТФИЗ', 'state', 'София',
 'https://natfiz.bg',
 NULL),

('amtii-plovdiv',
 'Академия за музикално, танцово и изобразително изкуство „Проф. Асен Диамандиев"',
 'Academy of Music, Dance and Fine Arts "Prof. Assen Diamandiev"',
 'АМТИИ', 'state', 'Пловдив',
 'https://amti.bg',
 NULL),

('unibit-sofia',
 'Университет по библиотекознание и информационни технологии',
 'University of Library Studies and Information Technologies',
 'УниБИТ', 'state', 'София',
 'https://www.unibit.bg',
 NULL),

('vtu-kableshkov-sofia',
 'Висше транспортно училище „Тодор Каблешков"',
 'Todor Kableshkov University of Transport',
 'ВТУ-ТК', 'state', 'София',
 'https://www.vtu.bg',
 NULL),

('vsu-karavelov-sofia',
 'Висше строително училище „Любен Каравелов"',
 'Higher School of Civil Engineering "Lyuben Karavelov"',
 'ВСУ-ЛК', 'state', 'София',
 'https://www.vsu.bg',
 NULL),

('vutp-sofia',
 'Висше училище по телекомуникации и пощи',
 'Higher School of Telecommunications and Posts',
 'ВУТП', 'state', 'София',
 'https://www.utp.bg',
 NULL),

('amvr-sofia',
 'Академия на Министерството на вътрешните работи',
 'Academy of the Ministry of Interior',
 'АМВР', 'state', 'София',
 'https://academy.mvr.bg',
 NULL),

-- ── Military universities ─────────────────────────────────────────────────────
('nvu-vt',
 'Национален военен университет „Васил Левски"',
 'National Military University "Vasil Levski"',
 'НВУ', 'military', 'Велико Търново',
 'https://www.nvu.bg',
 NULL),

('vvmu-varna',
 'Висше военноморско училище „Никола Й. Вапцаров"',
 'Nikola Vaptsarov Naval Academy',
 'ВВМУ', 'military', 'Варна',
 'https://naval-acad.bg',
 NULL),

('vvvu-dolnamitropolia',
 'Висше военновъздушно училище „Георги Бенковски"',
 'Georgi Benkovski Bulgarian Air Force Academy',
 'ВВВУ', 'military', 'Долна Митрополия',
 'https://www.afacademy.bg',
 NULL),

('va-rakovski-sofia',
 'Военна академия „Г. С. Раковски"',
 'G. S. Rakovski Military Academy',
 'ВА', 'military', 'София',
 'https://www.rnda.bg',
 NULL),

-- ── Private universities ──────────────────────────────────────────────────────
('nbu-sofia',
 'Нов български университет',
 'New Bulgarian University',
 'НБУ', 'private', 'София',
 'https://nbu.bg',
 'https://www.nbu.bg/bg/kandidat-studenti/priem-i-obuchenie'),

('aubg-blagoevgrad',
 'Американски университет в България',
 'American University in Bulgaria',
 'АУБ', 'private', 'Благоевград',
 'https://www.aubg.edu',
 'https://www.aubg.edu/apply'),

('vfu-varna',
 'Варненски свободен университет „Черноризец Храбър"',
 'Varna Free University "Chernorizets Hrabar"',
 'ВСУ', 'private', 'Варна',
 'https://www.vfu.bg',
 NULL),

('bfu-burgas',
 'Бургаски свободен университет',
 'Burgas Free University',
 'БСУ', 'private', 'Бургас',
 'https://www.bfu.bg',
 NULL),

('ibs-botevgrad',
 'Международно висше бизнес училище',
 'International Business School',
 'МВБУ', 'private', 'Ботевград',
 'https://ibsedu.bg',
 NULL),

('uzf-sofia',
 'Университет по застраховане и финанси',
 'University of Insurance and Finance',
 'УЗФ', 'private', 'София',
 'https://uzf.bg',
 NULL),

('uard-plovdiv',
 'Висше училище по агробизнес и развитие на регионите',
 'University of Agribusiness and Rural Development',
 'ВУАРР', 'private', 'Пловдив',
 'https://www.uard.bg',
 'https://ksk.uard.bg'),

('vum-varna',
 'Висше училище по мениджмънт',
 'Varna University of Management',
 'ВУМ', 'private', 'Варна',
 'https://vum.bg',
 NULL),

('anis-plovdiv',
 'Академия по национална и информационна сигурност',
 'Academy of National and Information Security',
 'АНИС', 'private', 'Пловдив',
 'https://www.vusi.bg',
 NULL),

('evuim-plovdiv',
 'Европейско висше училище по икономика и мениджмънт',
 'European Higher School of Economics and Management',
 'ЕВУИМ', 'private', 'Пловдив',
 NULL,
 NULL),

('kmtm-sofia',
 'Колеж по мениджмънт, търговия и маркетинг',
 'College of Management, Trade and Marketing',
 'КМТМ', 'private', 'София',
 NULL,
 NULL),

('kt-blagoevgrad',
 'Колеж по туризъм — Благоевград',
 'College of Tourism — Blagoevgrad',
 'КТ', 'private', 'Благоевград',
 NULL,
 NULL),

('epu-pernik',
 'Европейски политехнически университет',
 'European Polytechnic University',
 'ЕПУ', 'private', 'Перник',
 NULL,
 NULL)

ON CONFLICT (slug) DO UPDATE SET
    name_bg        = EXCLUDED.name_bg,
    name_en        = EXCLUDED.name_en,
    short_name_bg  = EXCLUDED.short_name_bg,
    ownership      = EXCLUDED.ownership,
    city           = EXCLUDED.city,
    website_url    = EXCLUDED.website_url,
    admissions_url = EXCLUDED.admissions_url,
    updated_at     = now();

SELECT count(*) AS institutions_total FROM institution;
